"use client";

import { CheckIcon, CopyIcon } from "@phosphor-icons/react";
import { useState } from "react";
import { cn } from "@/lib/utils";

interface CodeBlockProps {
  code: string;
  html: string;
  className?: string;
}

export function CodeBlock({ code, html, className }: CodeBlockProps) {
  const [copied, setCopied] = useState(false);

  async function handleCopy() {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1500);
  }

  return (
    <div
      className={cn(
        "not-prose group/code relative my-6 overflow-hidden rounded-xl border border-border/60 bg-card shadow-sm",
        "[&_.shiki]:m-0 [&_.shiki]:overflow-x-auto [&_.shiki]:p-4 [&_.shiki]:font-mono [&_.shiki]:text-sm [&_.shiki]:leading-6",
        className
      )}
    >
      <button
        aria-label={copied ? "Copied code" : "Copy code"}
        className={cn(
          "absolute top-2 right-2 z-10 inline-flex cursor-pointer items-center gap-1.5 rounded-md border border-border/60 bg-background/90 px-2 py-1 font-medium text-muted-foreground text-xs opacity-0 shadow-sm backdrop-blur transition",
          "hover:text-foreground focus-visible:opacity-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/50 group-hover/code:opacity-100"
        )}
        onClick={handleCopy}
        type="button"
      >
        {copied ? (
          <CheckIcon className="size-3.5" />
        ) : (
          <CopyIcon className="size-3.5" />
        )}
        {copied ? "Copied" : "Copy"}
      </button>

      <div
        // biome-ignore lint/security/noDangerouslySetInnerHtml: HTML is generated by Shiki from Marble-sanitized code blocks.
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  );
}
